image: registry.gitlab.com/qm64/packer/toolchain:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - make clean build
  except:
  - master
  artifacts:
    paths:
      - public
    expire_in: 1 day

pages:
  script:
  - make clean build
  artifacts:
    paths:
    - public
  only:
  - master
