baseURL = "https://qm64.tech/"
languageCode = "en-us"
title = "Qm64"
description = "Exploring new way to solve complexity using code and imagination"
relativeURLs = true

disqusShortname = "qm64"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  author = "authors"
  tag = "tags"
