baseURL: "https://blog.setale.me/"
languageCode: "en-us"
title: "Lorenzo Setale's Blog"
description: "My personal blog"
relativeURLs: true
enableRobotsTXT: true
mainSections: ["posts"]
enableEmoji: true
enableGitInfo: true

lastmod: ["lastmod", ":git", "date", "publishDate"]

params:
  comments: false

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"

## Changes to import content from jekyll
permalinks:
  posts: "/:year/:month/:day/:slug/"

disablePathToLower: true

sitemap:
  changefreq: "weekly"
  filename: "sitemap.xml"
  priority: 0.5

related:
  includeNewer: true
  indices:
    - name: tags
      weight: 80
    - applyFilter: false
      name: fragmentrefs
      type: fragments
      weight: 50
    - name: date
      weight: 80
