baseURL = "https://blog.setale.me/"
languageCode = "en-us"
title = "Lorenzo Setale's Blog"
description = "My personal blog"
relativeURLs = true

mainSections = ["posts"]

enableGitInfo = true
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  author = "authors"
  tag = "tags"

## Changes to import content from jekyll
[permalinks]
  posts = "/:year/:month/:day/:slug/"

disablePathToLower = true
